#include <argp.h>
#include "version.h"    // Autogenerated by meson
#include "version.hpp"

const char *boardproxy_version = GIT_VERSION;

const char * argp_program_version = "boardproxy " GIT_VERSION;
