
command_template = "ssh -t psr-hw@rpi-psr sterm -b 2000 -s 115200 /dev/serial/by-id/{serial_id}"
socket_dir = "/run/psr-hw"

# TODO
# [sockets]
# wrproxy = { type = "wrproxy" }
# www = { type = "tcp", port = 80 }

[boards]
mzapo01 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00EM7L-if00-port0", ip_address = "10.35.95.50" }
mzapo02 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00ENK1-if00-port0", ip_address = "10.35.95.51" }
mzapo03 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00EO5X-if00-port0", ip_address = "10.35.95.52" }
mzapo04 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00EQSO-if00-port0", ip_address = "10.35.95.53" }
mzapo05 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00EREM-if00-port0", ip_address = "10.35.95.54" }
mzapo06 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00ERUW-if00-port0", ip_address = "10.35.95.55" }
mzapo07 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00F380-if00-port0", ip_address = "10.35.95.56" }
mzapo08 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DN00JRK2-if00-port0", ip_address = "10.35.95.57" }
mzapo09 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DN00JU72-if00-port0", ip_address = "10.35.95.58" }
mzapo10 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DN00JU7G-if00-port0", ip_address = "10.35.95.59" }
# mzapo11 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DT03LIF2-if00-port0", ip_address = "10.35.95.60" } -- broken reset
mzapo12 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00EMJK-if00-port0", ip_address = "10.35.95.61" }
mzapo13 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00EMV1-if00-port0", ip_address = "10.35.95.62" }
mzapo14 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00EP9D-if00-port0", ip_address = "10.35.95.63" }
mzapo15 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00EQVU-if00-port0", ip_address = "10.35.95.64" }
mzapo16 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00ERII-if00-port0", ip_address = "10.35.95.65" }
mzapo17 = { serial_id = "usb-FTDI_FT230X_Basic_UART_DJ00ERLN-if00-port0", ip_address = "10.35.95.66" }
