sock_dir = "/tmp/bp_test"

close_command_template = "echo XXX Closing {ip_address}"

[boards.brd1]
command = "bash -c 'echo This is board 1; sleep inf'"
ip_address = "127.0.0.1"

[boards.brd2]
command = "bash -c 'echo This is board 2; sleep inf'"
ip_address = "127.0.0.2"
close_command = "sh -c 'echo Bye bye; sleep 10; exit 1'"
