name: "Complie"
on:
  pull_request:
  push:
  schedule:
    - cron:  '0 0 * * Mon'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Register gcc problem matcher # After subprojects to not see their warings
      run: echo "::add-matcher::.github/problem-matchers/gcc.json"
    - name: Build with nix-build
      run: nix-build
